appusers/urls.py
from django.contrib import admin
from django.urls import path
from appusers import views

# TEMPLATE URLS!
app_name = 'appusers'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from appusers import views

app_name = 'appusers'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('admin/',admin.site.urls),
    path('appusers/', include('appusers.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

appusers/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # additional
    portfolio_site = models.URLField(blank=True)

    profile_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to ='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

appusers/forms.py
from django import forms 
from django.contrib.auth.models import User
from appusers.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

appusers/views.py
from django.shortcuts import render
from appusers.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in , Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
                 {'user_form':user_form,
                  'profile_form':profile_form,
                  'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account NOT ACTIVE")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password {}".format(username,password))

    else:
        return render(request,'basic_app/login.html',{})   

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
              <a class="nav-link" aria-current="page" href="{% url 'appusers:register' %}">Register</a>

              {% if user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
              {% else %}
                <li><a class="nav-link" href="{% url 'appusers:user_login' %}">Login</a></li>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    {% block body_block %}
    {% endblock %}
    
</body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

{% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html'%}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'appusers:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">

    </form>

</div>
{% endblock %}

templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
  {% if registered %}
    <h1>Thank you for registered!</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
    </form>
</div>
{% endif %}
{% endblock %}